### PR TITLE
Configurable Info string option implementation

### PR DESCRIPTION
**Pull request by Cypher1**
Fixes https://github.com/dylanowen/mdbook-graphviz/issues/1 and refactors some config/options management from https://github.com/dylanowen/mdbook-graphviz/pull/118

Note: This is a stacked change including
https://github.com/dylanowen/mdbook-graphviz/pull/118

### CODE REVIEW

**Comment by Cypher1** [comment]
@dylanowen Could I get a review for this?

**Review by dylanowen — DISMISSED** [review]
Thanks for this! The only missing pieces are updating the Readme and bumping the version (probably a minor bump)

**Comment by Cypher1** [comment]
Sorry @dylanowen I added some doc. Could you review?

**Review by dylanowen — APPROVED** [review]
👍

**Pull request merged**
