### PR TITLE
Add class to output div

### PR DESCRIPTION
**Pull request by mmicu**
Add class to the output `div` in order to easily add a common style among all the produced outputs (e.g. center all the output svg images - #26).

### CODE REVIEW

**Comment by Cypher1** [comment]
Mind adding a note in the readme?

**Review by Cypher1 — APPROVED** [review]

**Review by Cypher1 — APPROVED** [review]

**Comment by Cypher1** [comment]
Thanks for your contributions!

**Comment by mmicu** [comment]
@Cypher1, is it possible to create a release to include such change?

**Comment by mmicu** [comment]
> @dylanowen, @Cypher1, is it possible to create a release to include such change?

@dylanowen, @Cypher1. Sorry to insist, but any news on this?

**Comment by Cypher1** [comment]
Release 0.2.1 should now be available! Sorry for the delay

**Pull request merged**
